version: "3.9"

services:
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"

  neo4j:
    image: bitnami/neo4j:latest
    ports:
      - '7474:7474'
      - '7473:7473'
      - '7687:7687'
